import { Geist, Geist_Mono, Kanit, Cedarville_Cursive, Edu_NSW_ACT_Cursive } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const  kanit = Kanit({
  variable: "--font-kanit",
  weight: ["400", "700"], // specify available weights here!


})
const cursive = Edu_NSW_ACT_Cursive({
  variable: "--font-cursive",
  weight: ["400"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kanit.variable} ${cursive.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
